name: DEES_programming_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.1
  - ca-certificates=2019.11.28
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - freetype=2.10.0
  - geos=3.8.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - icu=64.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.0.0
  - jupyter_console=6.0.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcxx=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libtiff=4.1.0
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib-base=3.2.0
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - owslib=0.19.1
  - pandas=1.0.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - proj=6.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyepsg=0.4.0
  - pygments=2.5.2
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=2.5.0
  - pyqt=5.12.3
  - pyrsistent=0.15.7
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.1
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - shapely=1.7.0
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /Users/user/anaconda3/envs/DEES_programming_env

